---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: hcp-pxe-host2
  #namespace: hcp-pxe
  labels:
    infraenvs.agent-install.openshift.io: hcp-pxe-styx
    tenant-id: tenant2
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: host2
spec:
  automatedCleaningMode: disabled
  # This is the MAC address of the NIC that will be used to PXE boot the host
  bootMACAddress: 52:54:00:61:a1:77
  online: true
  rootDeviceHints:
    deviceName: /dev/vda