---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcp-pxe

resources:
  - namespace.yaml
  - infraenv-1.yaml
  - infraenv-2.yaml
  - bmh-host1.yaml
  - bmh-host2.yaml
  - pull-secret.yaml