---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmh-ipxe-bridge
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: bmh-ipxe-bridge
  annotations:
    kubernetes.io/service-account.name: bmh-ipxe-bridge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmh-ipxe-bridge
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - "metal3.io"
    resources:
      - baremetalhosts
    verbs:
      - get
      - list
  - apiGroups:
      - "agent-install.openshift.io"
    resources:
      - infraenvs
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bmh-ipxe-bridge
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bmh-ipxe-bridge
subjects:
  - kind: ServiceAccount
    name: bmh-ipxe-bridge